In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [3]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
a1 ##basic example of a multi dimensional array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
2 / a1

array([[2.        , 1.        , 0.66666667],
       [0.5       , 0.4       , 0.33333333],
       [0.28571429, 0.25      , 0.22222222]])

In [6]:
2 * a1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [7]:
2 + a1

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
np.ravel(a1) #converting from a multidimensional array to 1d array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a1 > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [10]:
a2 = np.random.randn(3, 3)

In [11]:
a2 #creates a 3X3 matrix with mean 0 and standard deviation of 1 [gaussian distribution]

array([[-1.69000814,  2.26439584, -0.61687349],
       [ 1.9768813 , -1.39833605,  0.01532632],
       [ 1.26355899, -0.70494223, -0.85892102]])

In [12]:
a2[0, 0]

-1.6900081447654691

In [13]:
a2[1, 0]

1.9768813020654303

In [14]:
a2[0, 1] #matrix_variable[row_number, column_number]

2.264395836777484

In [15]:
a2[0]

array([-1.69000814,  2.26439584, -0.61687349])

In [21]:
a2[:, 1] #how to output column but not row

array([ 2.26439584, -1.39833605, -0.70494223])

In [23]:
a2[1,: ] #how to output row instead of column

array([ 1.9768813 , -1.39833605,  0.01532632])