In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as smp
import scipy as sp
from sympy import *

In [13]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([2, 4, 6, 8, 10])
a3 = np.array([1, 6, 4, 3, 7])

In [14]:
a1[::2]

array([1, 3, 5])

In [15]:
a1[::3]

array([1, 4])

In [16]:
a1[::4] #it selects the first one by default since there is nothing else to select

array([1, 5])

In [17]:
a1[::5] #it selects the first one by default since there is nothing else to select

array([1])

In [19]:
a1[0::2]

array([1, 3, 5])

In [20]:
a1[a1 > 3]

array([4, 5])

In [22]:
np.array([a1 > 3])

array([[False, False, False,  True,  True]])

In [23]:
names = np.array(['Jim', 'Jale', 'John', 'Emily', 'Random'])

In [29]:
names

array(['Jim', 'Jale', 'John', 'Emily', 'Random'], dtype='<U6')

In [30]:
names[0]

'Jim'

In [35]:
first_letter = np.vectorize(lambda z: z[0])(names)=='J'
#this will use lanbda method and segreate each string from each section and read the first string and
#confirm whether the first string is J, if yes it will output true, else output false

In [36]:
first_letter

array([ True,  True,  True, False, False])

In [37]:
np.array(names[first_letter]) #created an array of strings where the name of the first person starts with J

array(['Jim', 'Jale', 'John'], dtype='<U6')

In [40]:
import numpy as np
version = np.__version__
configuration = np.show_config()

/lib/python3.11/site-packages/numpy/__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


{
  "Compilers": {
    "c": {
      "name": "emscripten",
      "linker": "ld.wasm",
      "version": "3.1.46",
      "commands": "/tmp/tmp5sfzyzgz/cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.37",
      "commands": "cython"
    },
    "c++": {
      "name": "emscripten",
      "linker": "ld.wasm",
      "version": "3.1.46",
      "commands": "/tmp/tmp5sfzyzgz/c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "wasm",
      "family": "wasm32",
      "endian": "little",
      "system": "emscripten"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "cross-compiled": true
  },
  "Build Dependencies": {
    "blas": {
      "name": "auto"
    },
    "lapack": {
      "name": "dep140686374407824",
      "found": true,
      "version": "1.26.1",
      "detection method": "internal",
      "include directory": "unknown",
      "lib director